### ISSUE TITLE
Php 7.4

### ISSUE THREAD

**Issue by Ramys** [pedroh-dev255/DashStore#1]
Boa tarde.
Tudo bem?
Parabéns pelo o projeto.
Esse sistema trabalha na versão Php 7.4, e o Mysql 8.3.0?
Alguns erros encontrados.

<html>
<body>
<font size="1" style="color: rgb(0, 0, 0); font-family: &quot;Times New Roman&quot;; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">
( ! ) Warning: mysqli_connect(): php_network_getaddresses: getaddrinfo failed: Este host n�o � conhecido. in C:\wamp64\www\dashboar_lojinha-main\db.php on line 7
--

1 | 0.0001 | 366760 | {main}( ) | ...\login.php:0
2 | 0.0002 | 367688 | require( 'C:\wamp64\www\dashboar_lojinha-main\db.php ) | ...\login.php:13
3 | 0.0003 | 368304 | mysqli_connect( $host = 'root', $user = '', $password = '3306', $database = 'controle_lojinha' ) | ...\db.php:7

</font><span style="color: rgb(0, 0, 0); font-family: &quot;Times New Roman&quot;; font-size: medium; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial; display: inline !important; float: none;">Connection failed: php_network_getaddresses: getaddrinfo failed: Este host n�o � conhecido.</span>
</body>
</html>( ! ) Warning: mysqli_connect(): php_network_getaddresses: getaddrinfo failed: Este host n�o � conhecido. in C:\wamp64\www\dashboar_lojinha-main\db.php on line 7
Call Stack
#	Time	Memory	Function	Location
1	0.0001	366760	{main}( )	...\login.php:0
2	0.0002	367688	require( 'C:\wamp64\www\dashboar_lojinha-main\db.php )	...\login.php:13
3	0.0003	368304	[mysqli_connect](http://www.php.net/function.mysqli-connect)( $host = 'root', $user = '', $password = '3306', $database = 'controle_lojinha' )	...\db.php:7

( ! ) Warning: mysqli_connect(): (HY000/2002): php_network_getaddresses: getaddrinfo failed: Este host n�o � conhecido. in C:\wamp64\www\dashboar_lojinha-main\db.php on line 7
Call Stack
#	Time	Memory	Function	Location
1	0.0001	366760	{main}( )	...\login.php:0
2	0.0002	367688	require( 'C:\wamp64\www\dashboar_lojinha-main\db.php )	...\login.php:13
3	0.0003	368304	[mysqli_connect](http://www.php.net/function.mysqli-connect)( $host = 'root', $user = '', $password = '3306', $database = 'controle_lojinha' )	...\db.php:7
Connection failed: php_network_getaddresses: getaddrinfo failed: Este host n�o � conhecido.

**Comment by pedroh-dev255** [comment]
Estou rodando o projeto com PHP: 8.0.30 e mysql: 8.0.30

O problema que se ta enfrentando é na configuração do teu .env
esta assim:
#MYSQL
DB_HOST=root
DB_USER=
DB_PASS=3306
DB_NAME=controle_lojinha

O correto para um host local usando o wamp seria:

#MYSQL
DB_HOST=localhost
DB_USER=root
DB_PASS=
DB_NAME=controle_lojinha

**Comment by Ramys** [comment]
Tem razão.
Obrigado pela ajuda.
e mais um vez parabéns pelo o projeto.
